[build]
  publish = "/"
  command = ""

[[redirects]]
  from = "/api/*"
  to = "https://kapsalon-adem.onrender.com/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/admin/login"
  to = "/admin/login.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200
  force = true
  conditions = {Role = ["admin"]}

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
  force = true

[build.environment]
  NODE_VERSION = "18"
