[build]
  publish = "/"
  command = ""

# API proxy
[[redirects]]
  from = "/api/*"
  to = "https://kapsalon-adem.onrender.com/api/:splat"
  status = 200
  force = true
  headers = {
    Access-Control-Allow-Origin = "*",
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS",
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization",
    Access-Control-Allow-Credentials = "true"
  }

# Admin routes
[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/admin/login"
  to = "/admin/login.html"
  status = 200
  force = true

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[build.environment]
  NODE_VERSION = "18"
